#!/bin/bash

#SBATCH --job-name=hydro
#SBATCH -n 2 -t 00:05:00
#SBATCH -p debug


# NAME:			hydro.job
# ------------------------------------------------------------------------------------------------------------------------------------------- #
# FUNCTIONALITY:        This job script runs the hydro code used in the HPC Ib lecture.
# DESIGNED FOR:         Piz Dora @ CSCS (on account "stud04") - if used somewhere else: adjust the paths correspondingly
# AUTHOR:               Mischa B. A. Knabenhans
# DATE:                 May 19, 2016
# ------------------------------------------------------------------------------------------------------------------------------------------- #

export DATE=`date +%F_%Hh%M`
srun ./hydro_mpi /home/ics/mischak/hydro/HYDRO/Input/input_sedov_100x100.nml > run$DATE.log



