#!/bin/bash

# The part of the makemovie script that implements the ffmpeg

#ffmpeg -f image2 -framerate 20 -pattern_type glob -i '*.png' -r 25 ../movie.mp4
ffmpeg -framerate 20 -pattern_type glob -i '*.png' -vf "fps=30, scale=800:800" -pix_fmt yuv420p -shortest  ../movie.mp4
