#!/home/ics/volker/Anaconda/bin/python
# ^ for python on zbox


# CURRENTLY DOESNT WORK. WILL LOOK INTO IT LATER.

#/users/biernack/Enthought/Canopy_64bit/User/bin/python 
# ^ for python on dora/ela

#/usr/bin/python # use this as shebang if on local machine



# Get the maximal density. Assuming it is to be found in the first output file.


import fortranfile
import numpy
from os import getcwd, path, mkdir #get currend work dir, check if dir exists, make new dir
from sys import argv # command line arguments
from matplotlib import use
use('Agg') #don't show anything unless I ask you to. So no need to get graphical all over ssh.
from matplotlib import pyplot


map_file = str(argv[1])

f = fortranfile.FortranFile(map_file)
[t, gamma] = f.readReals()
[nx,ny,nvar,nstep] = f.readInts()
dat = f.readReals()
f.close()

dat = numpy.array(dat)
maxden = max(dat)

print maxden


workdir = str(getcwd())


#outputfilename = 'picoutput/'+map_file
#extension = 'png'
#fig_path = workdir+'/'+outputfilename+'.'+extension

#print "saving ", fig_path
#pyplot.savefig(fig_path, format=extension, facecolor=fig.get_facecolor(), transparent=True, dpi=100)
#pyplot.close()

print "done"

