#!/bin/bash

# The part of the makemovie script that implements the ffmpeg

#ffmpeg -f image2 -framerate 20 -pattern_type glob -i '*.png' -r 25 ../movie.mp4

#Take filename as cmd line arg.
#If none is given, take movie.mp4

if [ "$#" -gt 1 ] || [ "$#" == 0 ] ; then
    echo "movie name is: ../movie.mp4"
    filename="../movie.mp4"
else
    filename="$1"
    echo "filename is:" $filename
fi


#ffmpeg -framerate 20 -pattern_type glob -i '*.png' -vf "fps=30, scale=800:800" -pix_fmt yuv420p -shortest "$filename" 
#ffmpeg -framerate 20 -pattern_type glob -i '*.png' -fmt yuv420p -shortest "$filename" 

ffmpeg -r 20 -f image2 -pattern_type glob -i '*.png' -f mp4 -q:v 0 -vcodec mpeg4 -r 20 "$filename"

#ffmpeg -f image2 -pattern_type glob -i '*.png' -c:v h264  "$filename"

