#!/home/ics/volker/Anaconda/bin/python
# ^ for python on zbox

#/users/biernack/Enthought/Canopy_64bit/User/bin/python 
# ^ for python on dora/ela

#/usr/bin/python # use this as shebang if on local machine

# This script is made to be executer by the makemovie script.
# It makes pngs out of fortran output.
# To be used via a bash script.
# creates a .png file with the same name in the same directory.



import fortranfile
import numpy
from os import getcwd, path, mkdir #get currend work dir, check if dir exists, make new dir
from sys import argv # command line arguments
from matplotlib import use
use('Agg') #don't show anything unless I ask you to. So no need to get graphical all over ssh.
from matplotlib import pyplot


nproc = int(argv[1])
map_files = []
global_nx=0

print "Reading in files."

#for i in range(0, nproc):
#    inputfile = str(argv[i+2])
#    map_files.append(inputfile)

    # read image data: get global nx
#    f = fortranfile.FortranFile(inputfile)
#    [t, gamma] = f.readReals()
#    [nx,ny,nvar,nstep] = f.readInts()
    #print "nx =", nx
#    global_nx += nx
#    f.close()

#data = numpy.array([])
for i in range(0, nproc):
    inputfile = str(argv[i+2])
#    print "inputfile", inputfile
    f = fortranfile.FortranFile(inputfile)
    [t, gamma] = f.readReals()
    [nx,ny,nvar,nstep] = f.readInts()
    temp_data = f.readReals()#.reshape(nvar, ny, nx)
    f.close()
    
    temp_data = numpy.array(temp_data)
    temp_data = temp_data.reshape(nvar, ny, nx)
    if (i == 0):
        data = temp_data
    else:
        data = numpy.concatenate((data, temp_data), axis=2)

# create empty data array
#data=numpy.zeros(nvar*ny*global_nx).reshape(nvar,ny,global_nx)
#x=0
# read in values
#for i in range(0, nproc):
#    inputfile = map_files[i]
#    f = fortranfile.FortranFile(inputfile)
#    [t, gamma] = f.readReals()
#    [nx,ny,nvar,nstep] = f.readInts()
#    print "nx", nx, nvar, x
#    print data.shape
#    #data[0:nvar,0:ny,x:x+nx] = 
#    temp_data = f.readReals().reshape(nvar, ny, nx)
#    for k in range(nx):
#        for j in range(ny):
#            data[0,j,k+x] = temp_data[0,j,k]
#    print "-----------------------------------------------"
#    print " ID = ", i
#    print temp_data
#    x += nx
#    f.close()

#print "global nx", global_nx
#print len(data)

#data = numpy.array(data)
#data = data.reshape(nvar,ny,global_nx)


#Plotting
fig = pyplot.figure(facecolor='white', figsize=(5,5), dpi=150)
ax = fig.add_subplot(1,1,1)

print "plotting"

im=ax.imshow(data[0,:,:],interpolation='none',cmap='Blues_r') 
fig.colorbar(im, fraction=0.046, pad=0.04)

workdir = str(getcwd())


outputfilename = 'picoutput/'+inputfile[:-6]
extension = 'png'
fig_path = workdir+'/'+outputfilename+'.'+extension

print "saving ", fig_path
pyplot.savefig(fig_path, format=extension, facecolor=fig.get_facecolor(), transparent=False, dpi=150)
pyplot.close()

print "done"

