#!/bin/bash

# creates a movie of HYDRO output files named movie.mp4
# execute in the directory where the outputs are


#check if subdir "picoutput" exists. if not, create it.

if [ -d "picoutput" ]; then
    echo "Directory picoutput already exists."
else
    mkdir -p picoutput
    echo "made new dir picoutput"
fi

for i in output_*; do
    hydropic_movie $i
done

cd picoutput
ffmpeg_makemovie
cd ..

echo "done"

