#!/bin/bash

# creates a movie of HYDRO output files named movie.mp4
# execute in the directory where the outputs are


for i in output_*; do
    hydropic_movie $i
done

cd picoutput
ffmpeg -f image2 -r 2 -pattern_type glob -i '*.png' -r 100 ../movie.mp4

cd ..

echo "done"


